// AlbumList.js
const AlbumList = [
    {
      id: 0,
      title: "Album One",
      artist: "Artist A",
      genre: "Pop",
      albumName: "First Album",
      hitSong: "Hit Song 1",
      year: 2001,
    },
    {
      id: 1,
      title: "Album Two",
      artist: "Artist B",
      genre: "Rock",
      albumName: "Second Album",
      hitSong: "Hit Song 2",
      year: 2002,
    },
    {
      id: 2,
      title: "Album Three",
      artist: "Artist C",
      genre: "Jazz",
      albumName: "Third Album",
      hitSong: "Hit Song 3",
      year: 2003,
    },
    {
      id: 3,
      title: "Album Four",
      artist: "Artist D",
      genre: "Hip Hop",
      albumName: "Fourth Album",
      hitSong: "Hit Song 4",
      year: 2004,
    },
    {
      id: 4,
      title: "Album Five",
      artist: "Artist E",
      genre: "Country",
      albumName: "Fifth Album",
      hitSong: "Hit Song 5",
      year: 2005,
    },
    {
      id: 5,
      title: "Album Six",
      artist: "Artist F",
      genre: "Blues",
      albumName: "Sixth Album",
      hitSong: "Hit Song 6",
      year: 2006,
    },
    {
      id: 6,
      title: "Album Seven",
      artist: "Artist G",
      genre: "Classical",
      albumName: "Seventh Album",
      hitSong: "Hit Song 7",
      year: 2007,
    },
    {
      id:7 ,
      title: "Album Eight",
      artist: "Artist H",
      genre: "Reggae",
      albumName: "Eighth Album",
      hitSong: "Hit Song 8",
      year: 2008,
    },
    {
      id: 8,  
      title: "Album Nine",
      artist: "Artist I",
      genre: "Metal",
      albumName: "Ninth Album",
      hitSong: "Hit Song 9",
      year: 2009,
    },
    {
      id: 9,
      title: "Album Ten",
      artist: "Artist J",
      genre: "Electronic",
      albumName: "Tenth Album",
      hitSong: "Hit Song 10",
      year: 2010,
    },
    {
      id: 10,
      title: "Album Eleven",
      artist: "Artist K",
      genre: "Pop",
      albumName: "Eleventh Album",
      hitSong: "Hit Song 11",
      year: 2011,
    },
    {
      id: 11,
      title: "Album Twelve",
      artist: "Artist L",
      genre: "Rock",
      albumName: "Twelfth Album",
      hitSong: "Hit Song 12",
      year: 2012,
    },
    {
      id: 12,
      title: "Album Thirteen",
      artist: "Artist M",
      genre: "Jazz",
      albumName: "Thirteenth Album",
      hitSong: "Hit Song 13",
      year: 2013,
    },
    {
      id: 13,
      title: "Album Fourteen",
      artist: "Artist N",
      genre: "Hip Hop",
      albumName: "Fourteenth Album",
      hitSong: "Hit Song 14",
      year: 2014,
    },
    {
      id: 14,
      title: "Album Fifteen",
      artist: "Artist O",
      genre: "Country",
      albumName: "Fifteenth Album",
      hitSong: "Hit Song 15",
      year: 2015,
    },
    { 
      id: 15,
      title: "Album Sixteen",
      artist: "Artist P",
      genre: "Blues",
      albumName: "Sixteenth Album",
      hitSong: "Hit Song 16",
      year: 2016,
    },
    {
      id: 16,
      title: "Album Seventeen",
      artist: "Artist Q",
      genre: "Classical",
      albumName: "Seventeenth Album",
      hitSong: "Hit Song 17",
      year: 2017,
    },
    {
      id: 17,
      title: "Album Eighteen",
      artist: "Artist R",
      genre: "Reggae",
      albumName: "Eighteenth Album",
      hitSong: "Hit Song 18",
      year: 2018,
    },
    {
      id: 18,
      title: "Album Nineteen",
      artist: "Artist S",
      genre: "Metal",
      albumName: "Nineteenth Album",
      hitSong: "Hit Song 19",
      year: 2019,
    },
    {
      id: 19,
      title: "Album Twenty",
      artist: "Artist T",
      genre: "Electronic",
      albumName: "Twentieth Album",
      hitSong: "Hit Song 20",
      year: 2020,
    },
    {
      id: 20,
      title: "Album Twenty-One",
      artist: "Artist U",
      genre: "Pop",
      albumName: "Twenty-First Album",
      hitSong: "Hit Song 21",
      year: 2021,
    },
    {
      id: 21,
      title: "Album Twenty-Two",
      artist: "Artist V",
      genre: "Rock",
      albumName: "Twenty-Second Album",
      hitSong: "Hit Song 22",
      year: 2022,
    },
    {
      id: 22,
      title: "Album Twenty-Three",
      artist: "Artist W",
      genre: "Jazz",
      albumName: "Twenty-Third Album",
      hitSong: "Hit Song 23",
      year: 2023,
    },
    {
      id: 23,
      title: "Album Twenty-Four",
      artist: "Artist X",
      genre: "Hip Hop",
      albumName: "Twenty-Fourth Album",
      hitSong: "Hit Song 24",
      year: 2024,
    },
    {
      id: 24,
      title: "Album Twenty-Five",
      artist: "Artist Y",
      genre: "Country",
      albumName: "Twenty-Fifth Album",
      hitSong: "Hit Song 25",
      year: 2025,
    },
    {
      id: 25,
      title: "Album Twenty-Six",
      artist: "Artist Z",
      genre: "Blues",
      albumName: "Twenty-Sixth Album",
      hitSong: "Hit Song 26",
      year: 2026,
    },
    {
      id: 26,
      title: "Album Twenty-Seven",
      artist: "Artist AA",
      genre: "Classical",
      albumName: "Twenty-Seventh Album",
      hitSong: "Hit Song 27",
      year: 2027,
    },
    {
      id: 27,
      title: "Album Twenty-Eight",
      artist: "Artist AB",
      genre: "Reggae",
      albumName: "Twenty-Eighth Album",
      hitSong: "Hit Song 28",
      year: 2028,
    },
    {
      id: 28,
      title: "Album Twenty-Nine",
      artist: "Artist AC",
      genre: "Metal",
      albumName: "Twenty-Ninth Album",
      hitSong: "Hit Song 29",
      year: 2029,
    },
    {
      id: 29,
      title: "Album Thirty",
      artist: "Artist AD",
      genre: "Electronic",
      albumName: "Thirtieth Album",
      hitSong: "Hit Song 30",
      year: 2030,
    },
  ];
   
  module.exports = AlbumList;